// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalCar.Infrastructure;

#nullable disable

namespace RentalCar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250428114218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalCar.Entities.Car", b =>
                {
                    b.Property<string>("VIN")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Mileage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearOfManufacture")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("VIN");

                    b.HasIndex("CarBrandId");

                    b.HasIndex("CarTypeId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            VIN = "B4F86B7EDF5D45BCA",
                            CarBrandId = 1,
                            CarModel = "RAV4",
                            CarTypeId = 1,
                            Description = "Compact SUV with great fuel efficiency.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://www.topgear.com/sites/default/files/2024/09/Toyota-RAV4-Hybrid-036.jpg",
                            IsAvailable = true,
                            Mileage = 15000m,
                            Name = "Toyota RAV4",
                            PricePerDay = 50.00m,
                            YearOfManufacture = 2020
                        },
                        new
                        {
                            VIN = "53AFC8435F7B4F73A",
                            CarBrandId = 1,
                            CarModel = "Highlander",
                            CarTypeId = 1,
                            Description = "Spacious 7-seater SUV.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://media.whichcar.com.au/uploads/2023/02/5884556b-2024_Toyota_Grand_Highlander_Kluger_01.jpg",
                            IsAvailable = true,
                            Mileage = 10000m,
                            Name = "Toyota Highlander",
                            PricePerDay = 65.00m,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            VIN = "2DC9BB393BB34B8FA",
                            CarBrandId = 1,
                            CarModel = "4Runner",
                            CarTypeId = 1,
                            Description = "Off-road capable SUV.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://media.ed.edmunds-media.com/toyota/4runner/2025/oem/2025_toyota_4runner_4dr-suv_limited_fq_oem_1_1280.jpg",
                            IsAvailable = true,
                            Mileage = 25000m,
                            Name = "Toyota 4Runner",
                            PricePerDay = 70.00m,
                            YearOfManufacture = 2019
                        },
                        new
                        {
                            VIN = "9F58DC1FE2874E789",
                            CarBrandId = 1,
                            CarModel = "Land Cruiser",
                            CarTypeId = 1,
                            Description = "Luxury off-road vehicle.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/2021_Toyota_Land_Cruiser_300_3.4_ZX_%28Colombia%29_front_view_04.png/960px-2021_Toyota_Land_Cruiser_300_3.4_ZX_%28Colombia%29_front_view_04.png",
                            IsAvailable = true,
                            Mileage = 5000m,
                            Name = "Toyota Land Cruiser",
                            PricePerDay = 120.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "B13FD9E98BA449219",
                            CarBrandId = 1,
                            CarModel = "Venza",
                            CarTypeId = 1,
                            Description = "Stylish crossover SUV.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdoSLEPuOLBPAyKuDSt2znlsj2i0zg3Zj5uA&s",
                            IsAvailable = true,
                            Mileage = 12000m,
                            Name = "Toyota Venza",
                            PricePerDay = 55.00m,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            VIN = "4466B4FA6C834F998",
                            CarBrandId = 1,
                            CarModel = "bZ4X",
                            CarTypeId = 1,
                            Description = "Toyota's electric SUV.",
                            FuelType = "Electric",
                            ImageUrl = "https://nextgen-images.cdn.dealersolutions.com.au/modular.multisite.dealer.solutions/wp-content/uploads/sites/1674/2024/02/28151424/Toyota-Pressroom-650c4be0-c60a-4a67-9771-79ca946cdb88-1200x675.jpeg?format=webp&width=1200",
                            IsAvailable = true,
                            Mileage = 3000m,
                            Name = "Toyota bZ4X",
                            PricePerDay = 60.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "AB6D22AC047843248",
                            CarBrandId = 1,
                            CarModel = "Camry",
                            CarTypeId = 2,
                            Description = "Reliable midsize sedan.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://redriven.com/wp-content/uploads/2024/07/Toyota-Camry-XV70-15-1024x683.jpg",
                            IsAvailable = true,
                            Mileage = 8000m,
                            Name = "Toyota Camry",
                            PricePerDay = 45.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "8E5EB01632F94470B",
                            CarBrandId = 1,
                            CarModel = "Avalon",
                            CarTypeId = 2,
                            Description = "Premium full-size sedan.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://bucket.dealervenom.com/robinson-toyota/uploads/2017/08/30205601/272617-min.jpg?fm=pjpg&ixlib=php-3.3.1",
                            IsAvailable = true,
                            Mileage = 12000m,
                            Name = "Toyota Avalon",
                            PricePerDay = 55.00m,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            VIN = "E1B986AF5BC84EDA9",
                            CarBrandId = 1,
                            CarModel = "Corolla",
                            CarTypeId = 2,
                            Description = "Compact and fuel-efficient.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/f/fe/Toyota_Corolla_Hybrid_%28E210%29_IMG_4338.jpg",
                            IsAvailable = true,
                            Mileage = 5000m,
                            Name = "Toyota Corolla",
                            PricePerDay = 35.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "2B0DB732485F4929A",
                            CarBrandId = 1,
                            CarModel = "Mirai",
                            CarTypeId = 2,
                            Description = "Hydrogen fuel cell vehicle.",
                            FuelType = "Hydrogen",
                            ImageUrl = "https://images.autodaily.com.au/2021/05/Toyota-Mirai-2021-UK-11.jpg",
                            IsAvailable = true,
                            Mileage = 2000m,
                            Name = "Toyota Mirai",
                            PricePerDay = 75.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "7EDCEA7DD61C4183A",
                            CarBrandId = 1,
                            CarModel = "Crown",
                            CarTypeId = 2,
                            Description = "Luxury sedan with elevated design.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://cdn.motor1.com/images/mgl/JvQ8Q/s1/2021-toyota-crown-update.webp",
                            IsAvailable = true,
                            Mileage = 4000m,
                            Name = "Toyota Crown",
                            PricePerDay = 65.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "AFD57038FF444C22B",
                            CarBrandId = 1,
                            CarModel = "Prius",
                            CarTypeId = 2,
                            Description = "Iconic hybrid sedan.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/f/fa/2016_Toyota_Prius_%28ZVW50L%29_Hybrid_liftback_%282016-04-02%29_01.jpg",
                            IsAvailable = false,
                            Mileage = 10000m,
                            Name = "Toyota Prius",
                            PricePerDay = 40.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "4FD4B23DD7924FCAA",
                            CarBrandId = 1,
                            CarModel = "Corolla Hatchback",
                            CarTypeId = 3,
                            Description = "Sporty and practical.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://www.motortrend.com/uploads/sites/5/2018/04/2019-Toyota-Corolla-Hatchback-XSE-front-three-quarter-02.jpg?w=768&width=768&q=75&format=webp",
                            IsAvailable = true,
                            Mileage = 5000m,
                            Name = "Toyota Corolla Hatchback",
                            PricePerDay = 40.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "EDBAE1B21CF140229",
                            CarBrandId = 1,
                            CarModel = "Prius Prime",
                            CarTypeId = 3,
                            Description = "Hybrid hatchback with EV mode.",
                            FuelType = "Plug-in Hybrid",
                            ImageUrl = "https://www.digitaltrends.com/wp-content/uploads/2023/07/2023-Toyota-Prius-Prime-front-three-quarter.jpeg?fit=1500%2C1000&p=1",
                            IsAvailable = true,
                            Mileage = 8000m,
                            Name = "Toyota Prius Prime",
                            PricePerDay = 50.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "DE83CD5AEA534DB19",
                            CarBrandId = 1,
                            CarModel = "GR Corolla",
                            CarTypeId = 3,
                            Description = "High-performance hot hatch.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://nextgen-images.cdn.dealersolutions.com.au/modular.multisite.dealer.solutions/wp-content/uploads/sites/1576/2022/04/05064930/63814_hr-scaled.jpg?format=webp&width=2560",
                            IsAvailable = true,
                            Mileage = 3000m,
                            Name = "Toyota GR Corolla",
                            PricePerDay = 80.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "CF83662C0C3C4EDDB",
                            CarBrandId = 1,
                            CarModel = "Supra",
                            CarTypeId = 4,
                            Description = "Sporty convertible with BMW roots.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://nextgen-images.cdn.dealersolutions.com.au/modular.multisite.dealer.solutions/wp-content/uploads/sites/1674/2022/09/12104523/64112_800.jpg?format=webp&width=800",
                            IsAvailable = true,
                            Mileage = 7000m,
                            Name = "Toyota Supra",
                            PricePerDay = 90.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "AAA4B1228BB444FC8",
                            CarBrandId = 1,
                            CarModel = "MR2 Spyder",
                            CarTypeId = 4,
                            Description = "Mid-engine roadster.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/2003-mr2-spyder-2-1599224809.jpg",
                            IsAvailable = true,
                            Mileage = 45000m,
                            Name = "Toyota MR2 Spyder",
                            PricePerDay = 60.00m,
                            YearOfManufacture = 2005
                        },
                        new
                        {
                            VIN = "4B37AFA83FC64F068",
                            CarBrandId = 1,
                            CarModel = "Celica",
                            CarTypeId = 4,
                            Description = "Classic 90s convertible.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/30eaf80ceaa3b7a461a21047b172db29a6c3daa6/photos/Kdx27R15-D57YR1EU0r-(edit).jpg?t=171419188311",
                            IsAvailable = true,
                            Mileage = 60000m,
                            Name = "Toyota Celica Convertible",
                            PricePerDay = 45.00m,
                            YearOfManufacture = 2000
                        },
                        new
                        {
                            VIN = "E8AF438F314F4CE38",
                            CarBrandId = 1,
                            CarModel = "Soarer",
                            CarTypeId = 4,
                            Description = "Vintage luxury convertible.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://www.japancardirect.com/wp-content/uploads/2023/01/UZZ40-0009500_2_vga-640x456-1-640x420.jpg",
                            IsAvailable = false,
                            Mileage = 80000m,
                            Name = "Toyota Soarer Convertible",
                            PricePerDay = 55.00m,
                            YearOfManufacture = 1995
                        },
                        new
                        {
                            VIN = "6D3A7C141ADA48FEA",
                            CarBrandId = 2,
                            CarModel = "CR-V",
                            CarTypeId = 1,
                            Description = "Best-selling compact SUV.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://i0.wp.com/practicalmotoring.com.au/wp-content/uploads/2017/07/Honda-CR-V-VTi-LX-16.jpg?fit=768%2C526&ssl=1",
                            IsAvailable = false,
                            Mileage = 18000m,
                            Name = "Honda CR-V",
                            PricePerDay = 52.00m,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            VIN = "1ACCC27361EC4BE89",
                            CarBrandId = 2,
                            CarModel = "Pilot",
                            CarTypeId = 1,
                            Description = "Family-friendly 8-seater.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://www.usnews.com/object/image/0000018c-457f-dc8f-addc-ef7fda470001/24-honda-pilot-ext1.jpg?update-time=1701973208102&size=responsiveGallery",
                            IsAvailable = true,
                            Mileage = 20000m,
                            Name = "Honda Pilot",
                            PricePerDay = 60.00m,
                            YearOfManufacture = 2020
                        },
                        new
                        {
                            VIN = "AB88EF88C7E64D9F9",
                            CarBrandId = 2,
                            CarModel = "e:NS1",
                            CarTypeId = 1,
                            Description = "Honda's electric SUV.",
                            FuelType = "Electric",
                            ImageUrl = "https://marketplace.china-crunch.com/cdn/shop/files/honda_e_ns1_evmarketplace_chinacrunch_02.png?v=1689441717",
                            IsAvailable = true,
                            Mileage = 2000m,
                            Name = "Honda e:NS1",
                            PricePerDay = 55.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "6DDBE327344D4D7B8",
                            CarBrandId = 2,
                            CarModel = "Accord",
                            CarTypeId = 2,
                            Description = "Sleek midsize sedan.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/2023_Honda_Accord_LX%2C_front_left%2C_07-13-2023.jpg/960px-2023_Honda_Accord_LX%2C_front_left%2C_07-13-2023.jpg",
                            IsAvailable = true,
                            Mileage = 6000m,
                            Name = "Honda Accord",
                            PricePerDay = 48.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "AAC00E53569D437CB",
                            CarBrandId = 2,
                            CarModel = "Civic",
                            CarTypeId = 2,
                            Description = "Popular compact sedan.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Honda_Civic_e-HEV_Sport_%28XI%29_%E2%80%93_f_30062024.jpg/960px-Honda_Civic_e-HEV_Sport_%28XI%29_%E2%80%93_f_30062024.jpg",
                            IsAvailable = true,
                            Mileage = 10000m,
                            Name = "Honda Civic",
                            PricePerDay = 42.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "69DB84D2876B4E409",
                            CarBrandId = 2,
                            CarModel = "Insight",
                            CarTypeId = 2,
                            Description = "Fuel-efficient hybrid sedan.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://www.driva.com.au/static/971605b37cc6166334ea45d03e5963d9/6b6b2/6073b3bb-9dc9-4277-a094-3f78d58d2a55_image5.jpg",
                            IsAvailable = true,
                            Mileage = 12000m,
                            Name = "Honda Insight",
                            PricePerDay = 50.00m,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            VIN = "D32D080C17A64C69A",
                            CarBrandId = 2,
                            CarModel = "Civic Hatchback",
                            CarTypeId = 3,
                            Description = "Sporty and practical hatch.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://carsguide-res.cloudinary.com/image/upload/c_fit,h_841,w_1490,f_auto,t_cg_base/v1/editorial/2017-civic-hatch-(3).jpg",
                            IsAvailable = true,
                            Mileage = 5000m,
                            Name = "Honda Civic Hatchback",
                            PricePerDay = 45.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "E8A52964EF0243FEA",
                            CarBrandId = 2,
                            CarModel = "Fit",
                            CarTypeId = 3,
                            Description = "Ultra-spacious subcompact.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://www.cnet.com/a/img/resize/f970bb01b111c14e98d648df6a5e3ca17a233d3e/hub/2018/05/23/7173ead9-6e73-43e9-81b6-7e2cf165bc18/2018-honda-fit-promo.jpg?auto=webp&fit=crop&height=675&width=1200",
                            IsAvailable = true,
                            Mileage = 15000m,
                            Name = "Honda Fit",
                            PricePerDay = 35.00m,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            VIN = "D93F663BFBE7452EB",
                            CarBrandId = 2,
                            CarModel = "Jazz",
                            CarTypeId = 3,
                            Description = "Global name for the Honda Fit.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://i.ytimg.com/vi/yGRqTkx7vzk/hqdefault.jpg",
                            IsAvailable = true,
                            Mileage = 10000m,
                            Name = "Honda Jazz",
                            PricePerDay = 36.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "29C842DF4DC54700A",
                            CarBrandId = 2,
                            CarModel = "S2000",
                            CarTypeId = 4,
                            Description = "Legendary high-revving roadster.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/d/dc/HondaS2000-004.jpg",
                            IsAvailable = true,
                            Mileage = 30000m,
                            Name = "Honda S2000",
                            PricePerDay = 100.00m,
                            YearOfManufacture = 2009
                        },
                        new
                        {
                            VIN = "70652F8FDF784595A",
                            CarBrandId = 2,
                            CarModel = "Del Sol",
                            CarTypeId = 4,
                            Description = "90s targa-top convertible.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/1994_Honda_Civic_del_Sol_Si.jpg/1200px-1994_Honda_Civic_del_Sol_Si.jpg",
                            IsAvailable = true,
                            Mileage = 60000m,
                            Name = "Honda Del Sol",
                            PricePerDay = 45.00m,
                            YearOfManufacture = 1997
                        },
                        new
                        {
                            VIN = "00AC159762974A10B",
                            CarBrandId = 2,
                            CarModel = "Beat",
                            CarTypeId = 4,
                            Description = "Kei-car roadster.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://carsales.pxcrush.net/carsales/car/dealer/f08bafd961687e9e1ea8d73e3d1325e6.jpg?pxc_method=fitfill&pxc_bgtype=self&pxc_size=720,480",
                            IsAvailable = false,
                            Mileage = 50000m,
                            Name = "Honda Beat",
                            PricePerDay = 50.00m,
                            YearOfManufacture = 1995
                        },
                        new
                        {
                            VIN = "E6A22FEEC5A94641B",
                            CarBrandId = 3,
                            CarModel = "Explorer",
                            CarTypeId = 1,
                            Description = "Rugged family SUV.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://www.carpro.com/hs-fs/hubfs/2025-Ford-Explorer-ST-hero-credit-ford.jpg?width=1020&name=2025-Ford-Explorer-ST-hero-credit-ford.jpg",
                            IsAvailable = true,
                            Mileage = 15000m,
                            Name = "Ford Explorer",
                            PricePerDay = 58.00m,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            VIN = "6A35CB6C8B5C46CFA",
                            CarBrandId = 3,
                            CarModel = "Escape",
                            CarTypeId = 1,
                            Description = "Compact crossover SUV.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://images.carexpert.com.au/resize/3000/-/app/uploads/2023/04/2023-Ford-Escape-ST-Line-FWD_230414_Ford-Escape-ST-Line-FWD_Still-4.jpg",
                            IsAvailable = true,
                            Mileage = 10000m,
                            Name = "Ford Escape",
                            PricePerDay = 48.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "BD1EBAD76EEC421DA",
                            CarBrandId = 3,
                            CarModel = "Bronco",
                            CarTypeId = 1,
                            Description = "Iconic off-road SUV.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Ford_Bronco_%286th_generation%29_Outer_Banks_1X7A0384.jpg/1200px-Ford_Bronco_%286th_generation%29_Outer_Banks_1X7A0384.jpg",
                            IsAvailable = true,
                            Mileage = 5000m,
                            Name = "Ford Bronco",
                            PricePerDay = 70.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "D933DBA41C4D4931A",
                            CarBrandId = 3,
                            CarModel = "Fusion",
                            CarTypeId = 2,
                            Description = "Comfortable midsize sedan.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://www.vdm.ford.com/content/dam/brand_ford/en_us/brand/cars/fusion/sunset/FL10383620_FUSI_Hyb_SE_34FrntPassStcVlctyBlueNight_mj_16x9.jpg/jcr:content/renditions/cq5dam.web.768.768.jpeg",
                            IsAvailable = true,
                            Mileage = 22000m,
                            Name = "Ford Fusion",
                            PricePerDay = 46.00m,
                            YearOfManufacture = 2020
                        },
                        new
                        {
                            VIN = "7364F8738833413D8",
                            CarBrandId = 3,
                            CarModel = "Taurus",
                            CarTypeId = 2,
                            Description = "Full-size sedan with space.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/05-07_Ford_Taurus_SE_sedan.jpg/1200px-05-07_Ford_Taurus_SE_sedan.jpg",
                            IsAvailable = true,
                            Mileage = 25000m,
                            Name = "Ford Taurus",
                            PricePerDay = 50.00m,
                            YearOfManufacture = 2019
                        },
                        new
                        {
                            VIN = "D7FB570286F143D98",
                            CarBrandId = 3,
                            CarModel = "Focus",
                            CarTypeId = 2,
                            Description = "Compact and efficient.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://redriven.com/wp-content/uploads/2024/11/Ford-Focus-ST-1-scaled.jpg",
                            IsAvailable = true,
                            Mileage = 30000m,
                            Name = "Ford Focus",
                            PricePerDay = 40.00m,
                            YearOfManufacture = 2018
                        },
                        new
                        {
                            VIN = "F8A6722F7EF94D21B",
                            CarBrandId = 3,
                            CarModel = "Focus ST",
                            CarTypeId = 3,
                            Description = "Hot hatch performance model.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://www.topgear.com/sites/default/files/cars-car/inline-gallery/2024/10/1-Ford-Focus-ST-Edition-review-2024.jpg",
                            IsAvailable = false,
                            Mileage = 20000m,
                            Name = "Ford Focus ST",
                            PricePerDay = 55.00m,
                            YearOfManufacture = 2020
                        },
                        new
                        {
                            VIN = "183ED369F7914A949",
                            CarBrandId = 3,
                            CarModel = "Fiesta ST",
                            CarTypeId = 3,
                            Description = "Small but sporty hatchback.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.carexpert.com.au/resize/3000/-/app/uploads/2022/09/ford-fiesta-st-58.jpg",
                            IsAvailable = true,
                            Mileage = 25000m,
                            Name = "Ford Fiesta ST",
                            PricePerDay = 50.00m,
                            YearOfManufacture = 2019
                        },
                        new
                        {
                            VIN = "B2F820FBD20F4C788",
                            CarBrandId = 3,
                            CarModel = "Puma",
                            CarTypeId = 3,
                            Description = "Stylish subcompact crossover.",
                            FuelType = "Hybrid",
                            ImageUrl = "https://www.topgear.com/sites/default/files/2024/09/Puma_IMHEV_ST_LINE_018.jpg",
                            IsAvailable = true,
                            Mileage = 10000m,
                            Name = "Ford Puma",
                            PricePerDay = 48.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "E7C341890D0F40AD8",
                            CarBrandId = 3,
                            CarModel = "Mustang Convertible",
                            CarTypeId = 4,
                            Description = "Iconic American muscle car.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://seven82files.s3.amazonaws.com/wp-content/uploads/2021/09/1965-Ford-Mustang-convertible-1.jpg",
                            IsAvailable = true,
                            Mileage = 5000m,
                            Name = "Ford Mustang Convertible",
                            PricePerDay = 75.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "5BA1058C793341A7A",
                            CarBrandId = 3,
                            CarModel = "Thunderbird",
                            CarTypeId = 4,
                            Description = "Classic luxury convertible.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/5b/1957_Ford_Thunderbird_%2828911503716%29_%28cropped%29.jpg",
                            IsAvailable = true,
                            Mileage = 35000m,
                            Name = "Ford Thunderbird",
                            PricePerDay = 60.00m,
                            YearOfManufacture = 2005
                        },
                        new
                        {
                            VIN = "58605AF376FF4D868",
                            CarBrandId = 3,
                            CarModel = "Focus CC",
                            CarTypeId = 4,
                            Description = "Retractable hardtop convertible.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://media.autoexpress.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1562250430/autoexpress/images/car_photo_216766.jpg",
                            IsAvailable = true,
                            Mileage = 40000m,
                            Name = "Ford Focus CC",
                            PricePerDay = 45.00m,
                            YearOfManufacture = 2010
                        },
                        new
                        {
                            VIN = "5E63BAF3DEBE495C8",
                            CarBrandId = 4,
                            CarModel = "Tahoe",
                            CarTypeId = 1,
                            Description = "Full-size family SUV.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/22/2022_Chevrolet_Tahoe_RST%2C_front_3.7.22.jpg",
                            IsAvailable = true,
                            Mileage = 9000m,
                            Name = "Chevrolet Tahoe",
                            PricePerDay = 70.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "8090E20E3A8A41BD8",
                            CarBrandId = 4,
                            CarModel = "Suburban",
                            CarTypeId = 1,
                            Description = "Massive 9-seater SUV.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.carexpert.com.au/resize/3000/-/app/uploads/2023/12/chevrolet-suburban-1.jpg",
                            IsAvailable = true,
                            Mileage = 12000m,
                            Name = "Chevrolet Suburban",
                            PricePerDay = 80.00m,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            VIN = "F5A54530FD294656A",
                            CarBrandId = 4,
                            CarModel = "Equinox",
                            CarTypeId = 1,
                            Description = "Compact crossover SUV.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://media.ed.edmunds-media.com/chevrolet/equinox/2022/oem/2022_chevrolet_equinox_4dr-suv_rs_fq_oem_1_1600.jpg",
                            IsAvailable = true,
                            Mileage = 6000m,
                            Name = "Chevrolet Equinox",
                            PricePerDay = 55.00m,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            VIN = "E9883722348B4C0FB",
                            CarBrandId = 4,
                            CarModel = "Malibu",
                            CarTypeId = 2,
                            Description = "Comfortable midsize sedan.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Chevrolet_Malibu_LT_%28IX%2C_Facelift%29_%E2%80%93_f_02112024.jpg/1200px-Chevrolet_Malibu_LT_%28IX%2C_Facelift%29_%E2%80%93_f_02112024.jpg",
                            IsAvailable = true,
                            Mileage = 12000m,
                            Name = "Chevrolet Malibu",
                            PricePerDay = 48.00m,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            VIN = "E1C86921ACCD4522B",
                            CarBrandId = 4,
                            CarModel = "Impala",
                            CarTypeId = 2,
                            Description = "Classic full-size sedan.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Chevrolet_Impala_%2814373209694%29.jpg/330px-Chevrolet_Impala_%2814373209694%29.jpg",
                            IsAvailable = true,
                            Mileage = 18000m,
                            Name = "Chevrolet Impala",
                            PricePerDay = 52.00m,
                            YearOfManufacture = 2020
                        },
                        new
                        {
                            VIN = "EACF2621777E46258",
                            CarBrandId = 4,
                            CarModel = "Sonic",
                            CarTypeId = 2,
                            Description = "Compact budget sedan.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://cdn-fastly.thetruthaboutcars.com/media/2022/07/20/9417453/review-2012-chevrolet-sonic-lt.jpg?size=720x845&nocrop=1",
                            IsAvailable = false,
                            Mileage = 25000m,
                            Name = "Chevrolet Sonic",
                            PricePerDay = 38.00m,
                            YearOfManufacture = 2019
                        },
                        new
                        {
                            VIN = "7FE0CB5CA06B4046A",
                            CarBrandId = 4,
                            CarModel = "Bolt EV",
                            CarTypeId = 3,
                            Description = "Affordable electric hatchback.",
                            FuelType = "Electric",
                            ImageUrl = "https://bucket.dealervenom.com/2023/10/design22CHBO35004_960x500.jpg?auto=compress%2Cformat&ixlib=php-3.3.1",
                            IsAvailable = true,
                            Mileage = 5000m,
                            Name = "Chevrolet Bolt EV",
                            PricePerDay = 45.00m,
                            YearOfManufacture = 2023
                        });
                });

            modelBuilder.Entity("RentalCar.Entities.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chevrolet"
                        });
                });

            modelBuilder.Entity("RentalCar.Entities.CarReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RentalPeriod")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarReservations");
                });

            modelBuilder.Entity("RentalCar.Entities.CarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CarTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Convertible"
                        });
                });

            modelBuilder.Entity("RentalCar.Entities.Car", b =>
                {
                    b.HasOne("RentalCar.Entities.CarBrand", "CarBrand")
                        .WithMany("Cars")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalCar.Entities.CarType", "CarType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrand");

                    b.Navigation("CarType");
                });

            modelBuilder.Entity("RentalCar.Entities.CarReservation", b =>
                {
                    b.HasOne("RentalCar.Entities.Car", "Car")
                        .WithMany("CarReservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("RentalCar.Entities.Car", b =>
                {
                    b.Navigation("CarReservations");
                });

            modelBuilder.Entity("RentalCar.Entities.CarBrand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("RentalCar.Entities.CarType", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
